# Generated by Django 3.0.5 on 2020-07-20 02:28

from django.db import migrations
import djongo.models.fields
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200720_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=djongo.models.fields.EmbeddedField(blank=True, model_container=photo.models.Tag, null=True),
        ),
    ]
