# Generated by Django 3.0.5 on 2020-07-25 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200720_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='time',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='photo',
            name='decription',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_delated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
