# Generated by Django 3.0.8 on 2020-07-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, unique=True)),
                ('expiresAt', models.DateTimeField(blank=True)),
                ('refreshToken', models.CharField(max_length=512)),
                ('lastUpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
