# Generated by Django 3.0.5 on 2020-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
                ('refreshToken', models.CharField(max_length=512)),
                ('lastUpdateTime', models.DateTimeField(auto_now=True)),
                ('lastSync', models.DateTimeField(blank=True, null=True)),
                ('isSync', models.BooleanField(default=False)),
            ],
        ),
    ]
